/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExplorerRouteRouteImport } from './routes/explorer/route'
import { Route as CreatorRouteRouteImport } from './routes/creator/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SigninIndexRouteImport } from './routes/signin/index'
import { Route as ExplorerIndexRouteImport } from './routes/explorer/index'
import { Route as CreatorIndexRouteImport } from './routes/creator/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ExplorerPortfolioIndexRouteImport } from './routes/explorer/portfolio/index'
import { Route as ExplorerCalendarIndexRouteImport } from './routes/explorer/calendar/index'
import { Route as CreatorCalendarIndexRouteImport } from './routes/creator/calendar/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as CreatorProjectProjectIdRouteRouteImport } from './routes/creator/project/$projectId/route'
import { Route as ExplorerProjectProjectIdIndexRouteImport } from './routes/explorer/project/$projectId/index'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as CreatorProjectNewIndexRouteImport } from './routes/creator/project/new/index'
import { Route as CreatorProjectProjectIdIndexRouteImport } from './routes/creator/project/$projectId/index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as CreatorProjectProjectIdParticipantIndexRouteImport } from './routes/creator/project/$projectId/participant/index'
import { Route as CreatorProjectProjectIdMonitorIndexRouteImport } from './routes/creator/project/$projectId/monitor/index'

const ExplorerRouteRoute = ExplorerRouteRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRouteRoute = CreatorRouteRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerIndexRoute = ExplorerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExplorerRouteRoute,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ExplorerPortfolioIndexRoute = ExplorerPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => ExplorerRouteRoute,
} as any)
const ExplorerCalendarIndexRoute = ExplorerCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => ExplorerRouteRoute,
} as any)
const CreatorCalendarIndexRoute = CreatorCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => CreatorRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorProjectProjectIdRouteRoute =
  CreatorProjectProjectIdRouteRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => CreatorRouteRoute,
  } as any)
const ExplorerProjectProjectIdIndexRoute =
  ExplorerProjectProjectIdIndexRouteImport.update({
    id: '/project/$projectId/',
    path: '/project/$projectId/',
    getParentRoute: () => ExplorerRouteRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorProjectNewIndexRoute = CreatorProjectNewIndexRouteImport.update({
  id: '/project/new/',
  path: '/project/new/',
  getParentRoute: () => CreatorRouteRoute,
} as any)
const CreatorProjectProjectIdIndexRoute =
  CreatorProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CreatorProjectProjectIdRouteRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorProjectProjectIdParticipantIndexRoute =
  CreatorProjectProjectIdParticipantIndexRouteImport.update({
    id: '/participant/',
    path: '/participant/',
    getParentRoute: () => CreatorProjectProjectIdRouteRoute,
  } as any)
const CreatorProjectProjectIdMonitorIndexRoute =
  CreatorProjectProjectIdMonitorIndexRouteImport.update({
    id: '/monitor/',
    path: '/monitor/',
    getParentRoute: () => CreatorProjectProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/creator': typeof CreatorRouteRouteWithChildren
  '/explorer': typeof ExplorerRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/explorer/': typeof ExplorerIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/creator/project/$projectId': typeof CreatorProjectProjectIdRouteRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/creator/calendar/': typeof CreatorCalendarIndexRoute
  '/explorer/calendar/': typeof ExplorerCalendarIndexRoute
  '/explorer/portfolio/': typeof ExplorerPortfolioIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/creator/project/$projectId/': typeof CreatorProjectProjectIdIndexRoute
  '/creator/project/new/': typeof CreatorProjectNewIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/explorer/project/$projectId/': typeof ExplorerProjectProjectIdIndexRoute
  '/creator/project/$projectId/monitor/': typeof CreatorProjectProjectIdMonitorIndexRoute
  '/creator/project/$projectId/participant/': typeof CreatorProjectProjectIdParticipantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/explorer': typeof ExplorerIndexRoute
  '/signin': typeof SigninIndexRoute
  '/signup': typeof SignupIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/creator/calendar': typeof CreatorCalendarIndexRoute
  '/explorer/calendar': typeof ExplorerCalendarIndexRoute
  '/explorer/portfolio': typeof ExplorerPortfolioIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/creator/project/$projectId': typeof CreatorProjectProjectIdIndexRoute
  '/creator/project/new': typeof CreatorProjectNewIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/explorer/project/$projectId': typeof ExplorerProjectProjectIdIndexRoute
  '/creator/project/$projectId/monitor': typeof CreatorProjectProjectIdMonitorIndexRoute
  '/creator/project/$projectId/participant': typeof CreatorProjectProjectIdParticipantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/creator': typeof CreatorRouteRouteWithChildren
  '/explorer': typeof ExplorerRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/explorer/': typeof ExplorerIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/creator/project/$projectId': typeof CreatorProjectProjectIdRouteRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/creator/calendar/': typeof CreatorCalendarIndexRoute
  '/explorer/calendar/': typeof ExplorerCalendarIndexRoute
  '/explorer/portfolio/': typeof ExplorerPortfolioIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/creator/project/$projectId/': typeof CreatorProjectProjectIdIndexRoute
  '/creator/project/new/': typeof CreatorProjectNewIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/explorer/project/$projectId/': typeof ExplorerProjectProjectIdIndexRoute
  '/creator/project/$projectId/monitor/': typeof CreatorProjectProjectIdMonitorIndexRoute
  '/creator/project/$projectId/participant/': typeof CreatorProjectProjectIdParticipantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/creator'
    | '/explorer'
    | '/admin/'
    | '/creator/'
    | '/explorer/'
    | '/signin/'
    | '/signup/'
    | '/creator/project/$projectId'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/settings/'
    | '/admin/users/'
    | '/creator/calendar/'
    | '/explorer/calendar/'
    | '/explorer/portfolio/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/creator/project/$projectId/'
    | '/creator/project/new/'
    | '/demo/start/ssr/'
    | '/explorer/project/$projectId/'
    | '/creator/project/$projectId/monitor/'
    | '/creator/project/$projectId/participant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/creator'
    | '/explorer'
    | '/signin'
    | '/signup'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/settings'
    | '/admin/users'
    | '/creator/calendar'
    | '/explorer/calendar'
    | '/explorer/portfolio'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/creator/project/$projectId'
    | '/creator/project/new'
    | '/demo/start/ssr'
    | '/explorer/project/$projectId'
    | '/creator/project/$projectId/monitor'
    | '/creator/project/$projectId/participant'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/creator'
    | '/explorer'
    | '/admin/'
    | '/creator/'
    | '/explorer/'
    | '/signin/'
    | '/signup/'
    | '/creator/project/$projectId'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/settings/'
    | '/admin/users/'
    | '/creator/calendar/'
    | '/explorer/calendar/'
    | '/explorer/portfolio/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/creator/project/$projectId/'
    | '/creator/project/new/'
    | '/demo/start/ssr/'
    | '/explorer/project/$projectId/'
    | '/creator/project/$projectId/monitor/'
    | '/creator/project/$projectId/participant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CreatorRouteRoute: typeof CreatorRouteRouteWithChildren
  ExplorerRouteRoute: typeof ExplorerRouteRouteWithChildren
  SigninIndexRoute: typeof SigninIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer/': {
      id: '/explorer/'
      path: '/'
      fullPath: '/explorer/'
      preLoaderRoute: typeof ExplorerIndexRouteImport
      parentRoute: typeof ExplorerRouteRoute
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/explorer/portfolio/': {
      id: '/explorer/portfolio/'
      path: '/portfolio'
      fullPath: '/explorer/portfolio/'
      preLoaderRoute: typeof ExplorerPortfolioIndexRouteImport
      parentRoute: typeof ExplorerRouteRoute
    }
    '/explorer/calendar/': {
      id: '/explorer/calendar/'
      path: '/calendar'
      fullPath: '/explorer/calendar/'
      preLoaderRoute: typeof ExplorerCalendarIndexRouteImport
      parentRoute: typeof ExplorerRouteRoute
    }
    '/creator/calendar/': {
      id: '/creator/calendar/'
      path: '/calendar'
      fullPath: '/creator/calendar/'
      preLoaderRoute: typeof CreatorCalendarIndexRouteImport
      parentRoute: typeof CreatorRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/project/$projectId': {
      id: '/creator/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/creator/project/$projectId'
      preLoaderRoute: typeof CreatorProjectProjectIdRouteRouteImport
      parentRoute: typeof CreatorRouteRoute
    }
    '/explorer/project/$projectId/': {
      id: '/explorer/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/explorer/project/$projectId/'
      preLoaderRoute: typeof ExplorerProjectProjectIdIndexRouteImport
      parentRoute: typeof ExplorerRouteRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/project/new/': {
      id: '/creator/project/new/'
      path: '/project/new'
      fullPath: '/creator/project/new/'
      preLoaderRoute: typeof CreatorProjectNewIndexRouteImport
      parentRoute: typeof CreatorRouteRoute
    }
    '/creator/project/$projectId/': {
      id: '/creator/project/$projectId/'
      path: '/'
      fullPath: '/creator/project/$projectId/'
      preLoaderRoute: typeof CreatorProjectProjectIdIndexRouteImport
      parentRoute: typeof CreatorProjectProjectIdRouteRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/project/$projectId/participant/': {
      id: '/creator/project/$projectId/participant/'
      path: '/participant'
      fullPath: '/creator/project/$projectId/participant/'
      preLoaderRoute: typeof CreatorProjectProjectIdParticipantIndexRouteImport
      parentRoute: typeof CreatorProjectProjectIdRouteRoute
    }
    '/creator/project/$projectId/monitor/': {
      id: '/creator/project/$projectId/monitor/'
      path: '/monitor'
      fullPath: '/creator/project/$projectId/monitor/'
      preLoaderRoute: typeof CreatorProjectProjectIdMonitorIndexRouteImport
      parentRoute: typeof CreatorProjectProjectIdRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CreatorProjectProjectIdRouteRouteChildren {
  CreatorProjectProjectIdIndexRoute: typeof CreatorProjectProjectIdIndexRoute
  CreatorProjectProjectIdMonitorIndexRoute: typeof CreatorProjectProjectIdMonitorIndexRoute
  CreatorProjectProjectIdParticipantIndexRoute: typeof CreatorProjectProjectIdParticipantIndexRoute
}

const CreatorProjectProjectIdRouteRouteChildren: CreatorProjectProjectIdRouteRouteChildren =
  {
    CreatorProjectProjectIdIndexRoute: CreatorProjectProjectIdIndexRoute,
    CreatorProjectProjectIdMonitorIndexRoute:
      CreatorProjectProjectIdMonitorIndexRoute,
    CreatorProjectProjectIdParticipantIndexRoute:
      CreatorProjectProjectIdParticipantIndexRoute,
  }

const CreatorProjectProjectIdRouteRouteWithChildren =
  CreatorProjectProjectIdRouteRoute._addFileChildren(
    CreatorProjectProjectIdRouteRouteChildren,
  )

interface CreatorRouteRouteChildren {
  CreatorIndexRoute: typeof CreatorIndexRoute
  CreatorProjectProjectIdRouteRoute: typeof CreatorProjectProjectIdRouteRouteWithChildren
  CreatorCalendarIndexRoute: typeof CreatorCalendarIndexRoute
  CreatorProjectNewIndexRoute: typeof CreatorProjectNewIndexRoute
}

const CreatorRouteRouteChildren: CreatorRouteRouteChildren = {
  CreatorIndexRoute: CreatorIndexRoute,
  CreatorProjectProjectIdRouteRoute:
    CreatorProjectProjectIdRouteRouteWithChildren,
  CreatorCalendarIndexRoute: CreatorCalendarIndexRoute,
  CreatorProjectNewIndexRoute: CreatorProjectNewIndexRoute,
}

const CreatorRouteRouteWithChildren = CreatorRouteRoute._addFileChildren(
  CreatorRouteRouteChildren,
)

interface ExplorerRouteRouteChildren {
  ExplorerIndexRoute: typeof ExplorerIndexRoute
  ExplorerCalendarIndexRoute: typeof ExplorerCalendarIndexRoute
  ExplorerPortfolioIndexRoute: typeof ExplorerPortfolioIndexRoute
  ExplorerProjectProjectIdIndexRoute: typeof ExplorerProjectProjectIdIndexRoute
}

const ExplorerRouteRouteChildren: ExplorerRouteRouteChildren = {
  ExplorerIndexRoute: ExplorerIndexRoute,
  ExplorerCalendarIndexRoute: ExplorerCalendarIndexRoute,
  ExplorerPortfolioIndexRoute: ExplorerPortfolioIndexRoute,
  ExplorerProjectProjectIdIndexRoute: ExplorerProjectProjectIdIndexRoute,
}

const ExplorerRouteRouteWithChildren = ExplorerRouteRoute._addFileChildren(
  ExplorerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CreatorRouteRoute: CreatorRouteRouteWithChildren,
  ExplorerRouteRoute: ExplorerRouteRouteWithChildren,
  SigninIndexRoute: SigninIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
