/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorerIndexRouteImport } from './routes/explorer/index'
import { Route as CreatorIndexRouteImport } from './routes/creator/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ExplorerPortfolioRouteImport } from './routes/explorer/portfolio'
import { Route as ExplorerCalendarRouteImport } from './routes/explorer/calendar'
import { Route as CreatorCalendarRouteImport } from './routes/creator/calendar'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as ExplorerProjectProjectIdRouteImport } from './routes/explorer/project.$projectId'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as CreatorProjectNewRouteImport } from './routes/creator/project/new'
import { Route as CreatorProjectProjectIdRouteImport } from './routes/creator/project.$projectId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as CreatorProjectProjectIdMonitorRouteImport } from './routes/creator/project/$projectId.monitor'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerIndexRoute = ExplorerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExplorerRoute,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ExplorerPortfolioRoute = ExplorerPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ExplorerRoute,
} as any)
const ExplorerCalendarRoute = ExplorerCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ExplorerRoute,
} as any)
const CreatorCalendarRoute = CreatorCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => CreatorRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const ExplorerProjectProjectIdRoute =
  ExplorerProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => ExplorerRoute,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorProjectNewRoute = CreatorProjectNewRouteImport.update({
  id: '/project/new',
  path: '/project/new',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorProjectProjectIdRoute = CreatorProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => CreatorRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorProjectProjectIdMonitorRoute =
  CreatorProjectProjectIdMonitorRouteImport.update({
    id: '/monitor',
    path: '/monitor',
    getParentRoute: () => CreatorProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/creator': typeof CreatorRouteWithChildren
  '/explorer': typeof ExplorerRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/creator/calendar': typeof CreatorCalendarRoute
  '/explorer/calendar': typeof ExplorerCalendarRoute
  '/explorer/portfolio': typeof ExplorerPortfolioRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/explorer/': typeof ExplorerIndexRoute
  '/creator/project/$projectId': typeof CreatorProjectProjectIdRouteWithChildren
  '/creator/project/new': typeof CreatorProjectNewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/explorer/project/$projectId': typeof ExplorerProjectProjectIdRoute
  '/creator/project/$projectId/monitor': typeof CreatorProjectProjectIdMonitorRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/creator/calendar': typeof CreatorCalendarRoute
  '/explorer/calendar': typeof ExplorerCalendarRoute
  '/explorer/portfolio': typeof ExplorerPortfolioRoute
  '/admin': typeof AdminIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/explorer': typeof ExplorerIndexRoute
  '/creator/project/$projectId': typeof CreatorProjectProjectIdRouteWithChildren
  '/creator/project/new': typeof CreatorProjectNewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/explorer/project/$projectId': typeof ExplorerProjectProjectIdRoute
  '/creator/project/$projectId/monitor': typeof CreatorProjectProjectIdMonitorRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/creator': typeof CreatorRouteWithChildren
  '/explorer': typeof ExplorerRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/creator/calendar': typeof CreatorCalendarRoute
  '/explorer/calendar': typeof ExplorerCalendarRoute
  '/explorer/portfolio': typeof ExplorerPortfolioRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/explorer/': typeof ExplorerIndexRoute
  '/creator/project/$projectId': typeof CreatorProjectProjectIdRouteWithChildren
  '/creator/project/new': typeof CreatorProjectNewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/explorer/project/$projectId': typeof ExplorerProjectProjectIdRoute
  '/creator/project/$projectId/monitor': typeof CreatorProjectProjectIdMonitorRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/creator'
    | '/explorer'
    | '/signin'
    | '/signup'
    | '/admin/settings'
    | '/admin/users'
    | '/creator/calendar'
    | '/explorer/calendar'
    | '/explorer/portfolio'
    | '/admin/'
    | '/creator/'
    | '/explorer/'
    | '/creator/project/$projectId'
    | '/creator/project/new'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/explorer/project/$projectId'
    | '/creator/project/$projectId/monitor'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/admin/settings'
    | '/admin/users'
    | '/creator/calendar'
    | '/explorer/calendar'
    | '/explorer/portfolio'
    | '/admin'
    | '/creator'
    | '/explorer'
    | '/creator/project/$projectId'
    | '/creator/project/new'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/explorer/project/$projectId'
    | '/creator/project/$projectId/monitor'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/creator'
    | '/explorer'
    | '/signin'
    | '/signup'
    | '/admin/settings'
    | '/admin/users'
    | '/creator/calendar'
    | '/explorer/calendar'
    | '/explorer/portfolio'
    | '/admin/'
    | '/creator/'
    | '/explorer/'
    | '/creator/project/$projectId'
    | '/creator/project/new'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/explorer/project/$projectId'
    | '/creator/project/$projectId/monitor'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CreatorRoute: typeof CreatorRouteWithChildren
  ExplorerRoute: typeof ExplorerRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer/': {
      id: '/explorer/'
      path: '/'
      fullPath: '/explorer/'
      preLoaderRoute: typeof ExplorerIndexRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/explorer/portfolio': {
      id: '/explorer/portfolio'
      path: '/portfolio'
      fullPath: '/explorer/portfolio'
      preLoaderRoute: typeof ExplorerPortfolioRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/explorer/calendar': {
      id: '/explorer/calendar'
      path: '/calendar'
      fullPath: '/explorer/calendar'
      preLoaderRoute: typeof ExplorerCalendarRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/creator/calendar': {
      id: '/creator/calendar'
      path: '/calendar'
      fullPath: '/creator/calendar'
      preLoaderRoute: typeof CreatorCalendarRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/explorer/project/$projectId': {
      id: '/explorer/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/explorer/project/$projectId'
      preLoaderRoute: typeof ExplorerProjectProjectIdRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/project/new': {
      id: '/creator/project/new'
      path: '/project/new'
      fullPath: '/creator/project/new'
      preLoaderRoute: typeof CreatorProjectNewRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/project/$projectId': {
      id: '/creator/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/creator/project/$projectId'
      preLoaderRoute: typeof CreatorProjectProjectIdRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/project/$projectId/monitor': {
      id: '/creator/project/$projectId/monitor'
      path: '/monitor'
      fullPath: '/creator/project/$projectId/monitor'
      preLoaderRoute: typeof CreatorProjectProjectIdMonitorRouteImport
      parentRoute: typeof CreatorProjectProjectIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CreatorProjectProjectIdRouteChildren {
  CreatorProjectProjectIdMonitorRoute: typeof CreatorProjectProjectIdMonitorRoute
}

const CreatorProjectProjectIdRouteChildren: CreatorProjectProjectIdRouteChildren =
  {
    CreatorProjectProjectIdMonitorRoute: CreatorProjectProjectIdMonitorRoute,
  }

const CreatorProjectProjectIdRouteWithChildren =
  CreatorProjectProjectIdRoute._addFileChildren(
    CreatorProjectProjectIdRouteChildren,
  )

interface CreatorRouteChildren {
  CreatorCalendarRoute: typeof CreatorCalendarRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
  CreatorProjectProjectIdRoute: typeof CreatorProjectProjectIdRouteWithChildren
  CreatorProjectNewRoute: typeof CreatorProjectNewRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorCalendarRoute: CreatorCalendarRoute,
  CreatorIndexRoute: CreatorIndexRoute,
  CreatorProjectProjectIdRoute: CreatorProjectProjectIdRouteWithChildren,
  CreatorProjectNewRoute: CreatorProjectNewRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface ExplorerRouteChildren {
  ExplorerCalendarRoute: typeof ExplorerCalendarRoute
  ExplorerPortfolioRoute: typeof ExplorerPortfolioRoute
  ExplorerIndexRoute: typeof ExplorerIndexRoute
  ExplorerProjectProjectIdRoute: typeof ExplorerProjectProjectIdRoute
}

const ExplorerRouteChildren: ExplorerRouteChildren = {
  ExplorerCalendarRoute: ExplorerCalendarRoute,
  ExplorerPortfolioRoute: ExplorerPortfolioRoute,
  ExplorerIndexRoute: ExplorerIndexRoute,
  ExplorerProjectProjectIdRoute: ExplorerProjectProjectIdRoute,
}

const ExplorerRouteWithChildren = ExplorerRoute._addFileChildren(
  ExplorerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CreatorRoute: CreatorRouteWithChildren,
  ExplorerRoute: ExplorerRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
